version: 2

models: 
  - name: ana_respondents
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - id_respondent
    meta:
      dagster: 
        group: analytic 
        